---
title: "reproduce WaPo analysis from acs data"
output: html_document
---

```{r setup, include=FALSE}
# knitr options
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, echo=FALSE}
# Libraries
library(tidyverse)
library(tidycensus)
library(sf)

# Variables
vars_initial_analysis <-
  c(
    total_pop_est = "B01003_001",
    bachelors = "B15003_022",
    median_household_income = "B06011_001"
  )
```


1. Get ACS data: proportion bachelor's degree or higher, median household income, total population

```{r}
initial_data <- 
  get_acs(
    geography = "county",
    variables = vars_initial_analysis,
    year = 2018
  ) %>%
  pivot_wider(
    id_cols = -moe,
    names_from = variable, 
    values_from = estimate
  ) %>%
  mutate_at(
    vars(GEOID, total_pop_est:bachelors), 
    as.integer
  ) %>%
  transmute(
    fips = GEOID,
    total_pop_est,
    median_household_income,
    prop_bachelors = bachelors / total_pop_est
  ) %>%
  arrange(desc(prop_bachelors, median_household_income))
```


2. Assign percentile rank to each and average (method from Washington Post article)

```{r}
scored <- 
  initial_data %>%
  mutate(
    bachelors_pct = percent_rank(prop_bachelors),
    income_pct = percent_rank(median_household_income),
    pct_ranking = (bachelors_pct + income_pct) / 2
  ) %>%
  drop_na(pct_ranking) %>%
  arrange(desc(pct_ranking))
  
```


3. Plot on map

```{r}
county_boundaries <- 
  ussf::boundaries(geography = "county") %>% 
  mutate(fips = as.integer(GEOID))

scored_counties <- 
  county_boundaries %>%
  left_join(scored, by = "fips")

scored_counties %>%
  ggplot() + 
  geom_sf(aes(fill = pct_ranking), size = 0.01) +
  scale_fill_viridis_c(
    values = 
      c(seq(0, 0.9, by = 0.1), 0.95, 0.99, 1)
  ) +
  theme_void()


```




