---
title: 
author: 
date: "`r Sys.Date()`"
output: 
  github_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
# Libraries
library(tidyverse)
library(tidycensus)

# Parameters

census_tracts_file <- "../data/appalachian_tracts_race.csv"
central_census_tracts_file <- "../data/central_appalachian_tracts_race.csv"
appalachian_counties_file <- "../data/appalachian_counties_fips.csv"

#===============================================================================

# Code
```


```{r}
appalachia_tracts_race <-
  census_tracts_file %>%
  read_csv(
    col_types = 
      cols(
        fips = col_character(),
        name = col_character(),
        prop_nonwhite = col_double(),
        .default = col_integer()
      )
  )

central_appalachia_tracts_race <- 
  central_census_tracts_file %>%
  read_csv(
    col_types = 
      cols(
        fips = col_character(),
        name = col_character(),
        prop_nonwhite = col_double(),
        .default = col_integer()
      )
  )

appalachia_tracts_race %>%
  arrange(desc(prop_nonwhite))

central_appalachia_tracts_race %>%
  arrange(desc(prop_nonwhite))
```



```{r}
median <- 
  appalachia_tracts_race %>% pull(prop_nonwhite) %>% median(na.rm = TRUE)

appalachia_tracts_race %>%
  drop_na(prop_nonwhite) %>%
  ggplot(aes(prop_nonwhite)) +
  geom_histogram(bins = 30) +
  geom_vline(xintercept = median, color = "grey") +
  geom_text(
    aes(
      x = median + 0.05, 
      y = 1000, 
      label = str_glue("Median:\n", round(median, 3)*100, "%")
    ),
    size = 3
  ) + 
  scale_x_continuous(labels = scales::label_percent()) +
  labs(
    title = "Census Tracts by Proportion Non-white, Appalachia",
    x = "Proportion of residents self-identified as non-white",
    y = "Count"
  )
```



```{r}
median <- 
  central_appalachia_tracts_race %>% pull(prop_nonwhite) %>% median(na.rm = TRUE)

central_appalachia_tracts_race %>%
  drop_na(prop_nonwhite) %>%
  ggplot(aes(prop_nonwhite)) +
  geom_histogram(bins = 30) +
  geom_vline(xintercept = median, color = "grey") +
  geom_text(
    aes(
      x = median + 0.05, 
      y = 1000, 
      label = str_glue("Median:\n", round(median, 3)*100, "%")
    ),
    size = 3
  ) + 
  scale_x_continuous(labels = scales::label_percent()) +
  labs(
    title = "Census Tracts by Proportion Non-white, Central Appalachia",
    x = "Proportion of residents self-identified as non-white",
    y = "Count"
  )
```




```{r}
central_appalachia_tracts_race %>%
  drop_na(total_population, prop_nonwhite) %>%
  ggplot(aes(total_population, prop_nonwhite)) + 
  geom_point(alpha = 0.6) +
  ggrepel::geom_text_repel(
    aes(label = name %>% str_remove("Census Tract")),
    data = 
      . %>% 
      filter(prop_nonwhite > 0.40) %>%
      distinct(county_fips, .keep_all = TRUE),
    size = 3,
    direction = "y",
    hjust = -1
  ) +
  scale_x_continuous(breaks = scales::breaks_width(1000)) +
  scale_y_continuous(
    breaks = scales::breaks_width(0.2),
    labels = scales::label_percent()
  ) +
  labs(
    title = "Central Appalachia by Census Tract",
    subtitle = "Labelled tracts have >40% POC population",
    y = "Prop. self-identified as non-white",
    x = "Total Population",
    caption = "Source: U.S. Census Bureau, American Community Survey, 2018"
  )
  
```


```{r}
appalachian_counties <- 
  appalachian_counties_file %>%
  read_csv(col_types = cols(fips = col_integer(), .default = col_character()))

app_state_fips <-
  appalachian_counties %>%
  transmute(
    state_fips = fips %/% 1000,
    state_name
  ) %>%
  distinct(state_fips, state_name)

appalachia_tracts_race %>%
  mutate(state_fips = county_fips %/% 1000) %>%
  left_join(app_state_fips, by = "state_fips") %>%
  drop_na(state_fips, prop_nonwhite) %>%
  ggplot(aes(fct_reorder(state_name, prop_nonwhite), prop_nonwhite)) +
  geom_boxplot() +
  scale_y_continuous(
    breaks = seq(0, 1, 0.2),
    labels = scales::label_percent(),
    limits = c(0, 1.3)
  ) +
  geom_text(
    aes(
      label = name %>% 
        str_remove("Census Tract") %>%
        str_remove("County") %>%
        str_remove_all("[:digit:]") %>%
        str_remove_all(",") %>%
        str_remove_all("\\.")
    ),
    data = 
      . %>% 
      group_by(state_name) %>%
      top_n(1, wt = prop_nonwhite),
    size = 3,
    hjust = 0.01
  ) + 
  coord_flip() +
  labs(
    title = "Census Tracts by Proportion Non-white, Appalachia",
    x = "State",
    y = "Proportion of residents self-identified as non-white",
    caption = "Source: U.S. Census Bureau, American Community Survey, 2018"
  )
  
```

```{r}

  
```

```{r}
label_counties <- function(x) {
  x %>% 
    str_remove("Census Tract") %>% 
    str_remove_all("[:digit:]") %>%
    str_remove(",")
}

central_appalachia_tracts_race %>%
  drop_na(total_population, prop_nonwhite) %>%
  filter(prop_nonwhite == 0) %>%
  ggplot(aes(fct_reorder(name, total_population), total_population)) + 
  geom_point(alpha = 0.6) +
  scale_x_discrete(
    labels = label_counties
  ) +
  coord_flip() +
  labs(
    title = "Census Tracts with 0% Recorded POC Population",
    subtitle = "Central Appalachia",
    y = "Total Population",
    x = "",
    caption = "Source: U.S. Census Bureau, American Community Survey, 2018"
  )
```


```{r}
central_appalachia_tracts_race %>%
  filter(prop_nonwhite > .6) %>%
  ggplot(aes(x = fct_reorder(name, prop_nonwhite), y = prop_nonwhite)) + 
  geom_point() + 
  scale_x_discrete(labels = label_counties) +
  scale_y_continuous(breaks = scales::breaks_width(0.05)) +
  coord_flip() +
  labs(
    title = "Census tracts in Central Appalachia >60% nonwhite",
    y = "Prop. of residents self-identified as non-white",
    x = ""
  )
```


