---
title: "Your own challenge"
output: 
  github_document:
    toc: true
---

```{r setup, include=FALSE}
# knitr options
knitr::opts_chunk$set(echo = TRUE)
```

## Overview

The goal of the Data Challenge Lab is to help you develop professional-level skills. C01 is a quarter-long project in which you will develop these skills by doing the work of a data scientist. In C01, you will:

* Choose a topic that interests you.
* Obtain the necessary data and wrangle it for analysis.
* Perform exploratory data analysis (EDA) on your data, asking and answering questions and gaining insights.
* Present your findings to your peers.

You will likely learn new skills, or deepen existing ones, by working on your C01. To help your teammates learn from what you learn, you will also:

* Turn an aspect of your project into an educational challenge that others on the team will complete.

You can use your C01 as an opportunity to explore a topic that interests you or to develop mastery in an area beyond what we cover in the rest of the class. 

Your C01 __does not__ need to be original work. We encourage you to start by recreating the work of other data scientists. For example, you might find an interesting analysis and visualization and recreate both from the original raw data. Once you’re familiar with the data and can recreate the past work, you can go further than the original data scientists by asking new questions and seeking additional insights.  

You will meet with Bill or Sara regularly over the course of the quarter to discuss your progress.

### Project deadlines

All deadlines are also in the [Calender](https://bit.ly/2FovniY).

Step 1: Project proposal 1

* Sun, Jan 12, 11:59 PM: Upload
* Fri, Jan 17, 6:30 PM: Confer with Bill or Sara

Step 2: Project proposal 2

* Sun, Jan 19, 11:59 PM: Upload
* Fri, Jan 24, 6:30 PM: Confer with Bill or Sara

Step 3: Progress report 1

* Sun, Feb 2, 11:59 PM: Upload
* Fri, Feb 7, 6:30 PM: Confer with Bill or Sara

Step 4: Progress report 2

* Mon, Feb 16, 11:59 PM: Upload
* Fri, Feb 21, 6:30 PM: Confer with Bill or Sara

Step 5: Challenge and solution for team

* Sun, Feb 23, 11:59 PM: Upload
* Thu, Feb 27, 6:30 PM: Confer with Bill or Sara (optional)
* Thu, Feb 27, 11:59 PM: Upload final challenge and solution for team
* Fri, Feb 28, 4:30 PM: 2-minute presentation of challenge to team

Step 6: Final report

* Thu, Mar 12, 6:30 PM: Confer with Bill or Sara (optional)
* Thu, Mar 12, 11:59 PM: Upload final report
* Thu, Mar 12, 4:30 PM or Fri, Mar 13, 4:30 PM: 2-minute presentation

### Project workflow folders

The folders __data__, __data_raw__, __docs__, __eda__, __scripts__, and __reports__ support a data science project workflow, as explained in [folder organization](https://dcl-workflow.stanford.edu/project-workflow.html#folder-organization). Over the course of your C01, we will help you to master this workflow.

### reports folder

The __reports__ folder contains step_*.Rmd files are to complete, knit, and upload for the C01 step milestones.

### team-challenge folder

The __team-challenge__ folder is where to put your challenge for the rest of the team and the solution. The folder contains a master.Rmd template file that can be used to automatically generate challenge.Rmd and solution.Rmd files, as well as answers.

## Step 1: Project proposal 1

Deadlines:

* Sun, Jan 12, 11:59 PM: Upload
* Fri, Jan 17, 6:30 PM: Confer with Bill or Sara

The first step of the project is to explore different possibilities for your own challenge. Your challenge should be something that:

* You find interesting.
* Has an aspect that can be turned into a challenge that others would find interesting.
* Uses data that is either publicly available or that Stanford has a license for.

Your project can be your own idea, or you can choose from the wide variety of

* [C01 challenge ideas](https://docs.google.com/document/d/1LoGoJWw_2Zpxg9kQOoJIa1mXxVq1SBbpvg72-CV3kWs/edit#)

we have collected from a variety of domains.

For the Step 1 milestone, you can have more than one idea for your project. For each idea, write up a brief description that contains:

* An overview of the project, the data, and the goals.
* Links to the data, or an explanation of how you will obtain the data.
* Links to the work of the original data scientists, if you are doing a re-creation.

To submit your project proposal, simply complete, knit, and upload the step_1_project_proposal_1.Rmd file in the __reports__ folder

## Step 2: Project proposal 2

Deadlines:

* Sun, Jan 19, 11:59 PM: Upload
* Fri, Jan 24, 6:30 PM: Confer with Bill or Sara

Using feedback on project proposal 1 and further work, create your project proposal 2. For your project idea, write up a brief description that contains:

* An overview of the project, the data, and the goals.
* Links to the data, or an explanation of how you will obtain the data.
* If a re-creation of the work of other data scientists, links to their work.
* The aspect that can be turned into a challenge for the rest of the team.
* A decomposition of the project into smaller parts with goals for the milestones:
    * Progress report 1 (week 4)
    * Progress report 2 (week 6)
    * Challenge for rest of the team (week 7)
    * Final report (week 9)

To submit your project proposal, simply complete, knit, and upload the step_2_project_proposal_2.Rmd file in the __reports__ folder.

## Step 3: Progress report 1

Deadlines:

* Sun, Feb 2, 11:59 PM: Upload
* Fri, Feb 7, 6:30 PM: Confer with Bill or Sara

By the step 3 deadline you will have had 2 weeks since the deadline for project proposal 2. The purpose of this milestone is to report on your progress over these 2 weeks. Your progress report 1 should include:

* A summary of your progress.
* Key findings and insights illustrated with visualizations.
* Any issues you are currently facing.
* Your plans for next steps.

To submit your project proposal, simply complete, knit, and upload the step_3_progress_report_1.Rmd file in the __reports__ folder.

## Step 4: Progress report 2

Deadlines:

* Sun, Feb 16, 11:59 PM: Upload
* Fri, Feb 21, 6:30 PM: Confer with Bill or Sara

By the step 4 deadline you will have had 2 weeks since the deadline for progress report 1. The purpose of this milestone is to report on your progress over these 2 weeks. By now you should have made substantial progress. Your progress report 2 should include:

* A summary of your progress.
* Key findings and insights illustrated with visualizations.
* Any issues you are currently facing.
* Your plans for your challenge for rest of team.
* Your plans for next steps.

To submit your project proposal, simply complete, knit, and upload the step_4_progress_report_2.Rmd file in the __reports__ folder.

## Step 5: Challenge and solution for team

Deadlines:

* Sun, Feb 23, 11:59 PM: Upload
* Thu, Feb 27, 6:30 PM: Confer with Bill and Sara (optional)
* Thu, Feb 27, 11:59 PM: Upload final challenge and solution for team
* Fri, Feb 28, 4:30 PM: 2-minute presentation of challenge to team

In this step, you will create a challenge for the rest of the team. Each team member should pair off with another member. Before submitting this step, you should read each other's challenge questions to make sure that they are clear and easily understandable.

<!--
We have created a [C01 challenge metadata spreadsheet](). Enter here a challenge name for your challenge, a description of what it will be, and the skills that it will exercise. Also, say whether or not you need storage for data or answers. If so, we will create space for you on Box.
-->

The __team-challenge__ folder is for your challenge and solution for the rest of the team. This folder contains a master.Rmd file and a Makefile. If you follow the instructions for editing the master.Rmd file, you can use Unix commands to automatically generate your challenge.Rmd and solution.Rmd files and an answer file. Once these files have been generated, be sure to knit them.

<!--
Bill and Sara will hold optional C01 office hours during week 8. If you would like to meet with Bill and Sara about your C01, fill in your available times on the [C01 office hours spreadsheet]().
-->

## Step 6: Final report

Deadlines:

* Thu, Mar 12, 6:30 PM: Confer with Bill and Sara (optional)
* Thu, Mar 12, 11:59 PM: Upload final report
* Thu, Mar 12, 4:30 PM or Fri, Mar 13, 4:30 PM: 2-minute presentation

<!--
Bill and Sara will hold optional C01 office hours during week 10. If you would like to meet with Bill and Sara about your C01, fill in your available times on the [C01 office hours spreadsheet]( and be sure to upload the current draft of your C01 before your meeting.
-->

Your final report is due on Thu, Mar 12. Analogous to a report by a professional data scientist, your report should summarize what you did and present your key findings and insights. Accompany the text of your findings with presentation-quality plots. Assume that your audience has little prior knowledge about your topic, and strive to present your findings in an engaging storyline.

To submit your final report, simply complete, knit, and upload the step_6_final_report.Rmd file in the __reports__ folder.
